name: fdp_generator
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  ninja: ^3.0.1
  validators: ^2.0.0
#   args: ^1.6.0
#   asn1lib: ^0.8.1
#   clock: ^1.0.1
#   collection: ^1.14.13
#   crypto: ^2.1.5
#   pointycastle: ^2.0.0
#  path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0

  
